### ISSUE TITLE
You can add more than just one like

### ISSUE THREAD

**Issue by dayoungcheong** [todo-name/TODO-NAME#1]
I signed up and was on the front dashboard. If I double click a heart, it actually raises the number of likes by 2, instead of liking it and unliking it. If I already liked the post and double click, it will decrease the number of likes by 2.

**Comment by lukepallen** [comment]
Fixed in commit:
https://github.com/todo-name/TODO-NAME/commit/ff596bf963cf503829fadf3c2ae1c0cab7e6c2c4
