### ISSUE TITLE
Bottom of page has text boxes

### ISSUE THREAD

**Issue by clairehjk** [todo-name/TODO-NAME#16]
I'm not sure if this intentional or not, if it is please ignore this issue.
I believe clicking the 3 dot -> Copy Link on the card produces text boxes containing their links at the very bottom of the page. 
1. Navigate to page
2. Click 3 dot -> copy link of gif (specifically the BAN one or the cute fluffy white dog one)
3. Scroll to bottom of page and you'll see the text boxes.

**Comment by s711258w** [comment]
Could not reproduce

**Comment by s711258w** [comment]
Fixed in commit 6891e3c
