### ISSUE TITLE
Infinite Likes Allowed

### ISSUE THREAD

**Issue by matthewkli97** [todo-name/TODO-NAME#2]
When users like an image and search is refreshed, the state/history is not maintained for the images liked by the user. This allows for users to be able to infinitely like images and increase like counts. This additionally does not allow users to identify images that they have already liked.

Reproduction Steps:
1. Sign into your account
2. Search anything in the bar that returns results
3. Like an image by clicking the heart icon.
4. Click search again.
5. Find the same image that you liked prior to the refresh.
6. Like the image again.
7. Repeat steps 4-6

See gif for reproduction:

![infinteLikes](https://user-images.githubusercontent.com/26758656/59231807-e1227d80-8b96-11e9-8e30-ccad4da809a1.gif)

**Comment by lukepallen** [comment]
Fixed in commit:
https://github.com/todo-name/TODO-NAME/commit/2a19e09d142f151c868100d4e43858b6a76899af
