### ISSUE TITLE
Not sure if image is required

### ISSUE THREAD

**Issue by yiranni** [todo-name/TODO-NAME#28]
When I upload, it tells me an image file is required, but I do see a couple of cards without images.
![image](https://user-images.githubusercontent.com/32496771/59304744-b34c4000-8c4d-11e9-9314-6a4a8b8de03c.png)

**Comment by Jimmt** [comment]
Image is required. Card appearing to have no image is actually just text overflow problem fixed in 41b81062820f7230811fd41ce126da5e213cabb2
