### ISSUE TITLE
Gif does not let me copy link

### ISSUE THREAD

**Issue by dayoungcheong** [todo-name/TODO-NAME#3]
I logged in and went down to the bottom of the feed where the gif of the dog getting hair dried was. I clicked the top right three buttons then clicked "copy link" for that card and it made me jump to the top of the page. When I tried to paste, nothing came out. The copy link functionality does not work for the gif of the dog getting blowdried.

**Comment by my828** [comment]
Real failure. Fixed. Commit hash: a3f2cf0bfe19e908cb0ec2b00938f07e913c53bc
