### ISSUE TITLE
Error message from sign up persists

### ISSUE THREAD

**Issue by JessicaXLou** [todo-name/TODO-NAME#31]
![image](https://user-images.githubusercontent.com/32353106/59309111-9583d880-8c57-11e9-9d7f-d326bce1dbec.png)
I tried signing in without and account and received the "There is no user record corresponding to this identifier. The user may have been deleted." error message. I then clicked on Sign up and the error message still persisted

**Comment by s711258w** [comment]
Duplicate error, already fixed
