### ISSUE TITLE
Confusing message after sign up

### ISSUE THREAD

**Issue by JessicaXLou** [todo-name/TODO-NAME#32]
![image](https://user-images.githubusercontent.com/32353106/59309221-eabfea00-8c57-11e9-8ee1-4b00837c251d.png)
After signing up, the pop up box that tells me that I have successfully signed up only has a "Cancel" button under, which is confusing. I assume it means "Complete", but the word cancel signifies that I might want to cancel my sign up.

**Comment by s711258w** [comment]
Fixed issue, duplicate of another issue
