### ISSUE TITLE
Clicking Like Button Really Fast Allows Negative Likes

### ISSUE THREAD

**Issue by emilytao19** [todo-name/TODO-NAME#4]
If you click the like button really fast the likes go into the negatives

**Comment by emilytao19** [comment]
<img width="370" alt="Screen Shot 2019-06-10 at 3 54 31 PM" src="https://user-images.githubusercontent.com/32439428/59232149-17acc800-8b98-11e9-89b5-3b31d6723e8d.png">

**Comment by lukepallen** [comment]
Fixed in commit:
https://github.com/todo-name/TODO-NAME/commit/ff596bf963cf503829fadf3c2ae1c0cab7e6c2c4
